title: Hello Github Pages
author: Tim Griffith
email: tim.griffith.dev@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Just learning the basics...

# social links
twitter_username: TheGrimTiffith
github_username: TheGrimTiffith

show_excerpts: true # set to false to remove excerpts on the homepage
